### ISSUE TITLE
Sprint issue list

### ISSUE THREAD

**Issue by lqez** [lqez/python-kr-sprint-201812#1]

**Comment by lqez** [comment]
https://code.djangoproject.com/ticket/30040

**Comment by lqez** [comment]
https://code.djangoproject.com/ticket/30004

**Comment by lqez** [comment]
https://code.djangoproject.com/ticket/29784

**Comment by lqez** [comment]
오탈자 예제 PR : https://github.com/django/django/pull/10689

**Comment by candypoplatte** [comment]
1st PR !!!!
https://github.com/django/django/pull/10756

**Comment by candypoplatte** [comment]
Ticket assigned!!
https://code.djangoproject.com/ticket/29186

**Comment by lqez** [comment]
I assigned myself to https://code.djangoproject.com/ticket/30040

**Comment by candypoplatte** [comment]
## `#29186` 이슈에 대하여...

`#29186` 이슈 요약과 `스프린트 팀`에서 논의한 내용을 정리합니다.

### 현상

SocketHandler를 Django에서 사용할 Logging Handler 목록에 추가하면, WSGIRequest 객체가 Pickling되지 못해서 에러가 남

### 어떻게 해결할까?

#### 1차 솔루션

- 의견
    - WSGIRequest 객체의 인스턴스 변수 중 피클링이 되지 않는 변수를 제거하고 보내자
- 피드백
    - SocketHandler 하나가 문제인건데, 하나 때문에 전체 핸들러로 전달되는 LogRecord 정보가 줄어드는 것은 불합리하다.

#### 2차 솔루션

- 의견
    - Django 설정에서 핸들러 목록에 SocketHandler를 선택하면 안 된다는 에러를 발생시키고 문서 작성을 하자
- 피드백
    - 그건 아예 싹을 잘라버리는 해결법이다. 오히려 정보량이 줄어든다는 경고와 함께 그 핸들러로만 피클링가능한 정보를 전달하는게 나을 것 같다.

#### 3차 솔루션 (최신)

- 의견
    - Django 설정에서 핸들러 목록에 SocketHandler이 선택되면 해당 핸들러로는 피클링이 가능하도록 정보량을 줄인 WSGIRequest 객체의 Reduced Version을 전달한다.
    - 그리고 경고(Warning) 및 문서화 필수

**Comment by candypoplatte** [comment]
### To Dos
- [ ] ReducedSocketHandler or SafeSocketHandler 클래스 추가 + Docstring 작성
    - SocketHandler를 상속하고 emit method만 overring 한다.
- [ ] logging 설정을 할 때 (`logging.config.dictConfig`) 핸들러 목록에 `logging.handlers.SocketHandler`가  있으면 `django.utils.log.ReducedSocketHandler`로 교체 + 경고 메시지
- [ ] Document 수정...?

**Comment by 2w3** [comment]
https://github.com/django/django/pull/10757

Fixed #30040 -- Documentation on permissions on templates is wrong

can_vote is not django standard permission expression.
so, fixed to can_vote to add_vote in permission detail expression.

related django bug report url:
https://code.djangoproject.com/ticket/30040

Thank you for my commit message reading.

**Comment by candypoplatte** [comment]
https://github.com/django/django/pull/10758

일단 PR 올림...!!!!

**Comment by lqez** [comment]
Nice job, Pythonistas!
